using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TVM.Models
{
    public class TwoVarEquation
    {
        public TwoVarEquation()
        {
            
        }

        public string[] equationName = {"Average Tax Rate",
                                        "Book Value of Assets",
                                        "Book Value Per Share",
                                        "Cash Flow from Assets",
                                        "Cash Flow to Creditors",
                                        "Cash Flow to Stockholders",
                                        "Change in Net Working Capital",
                                        "Current Ratio",
                                        "Days Sales in Inventory",
                                        "Days Sales in Recievables",
                                        "Dividends Per Share",
                                        "Earnings Per Share",
                                        "Inventory Turnover",
                                        "Market to Book Ratio",
                                        "Market Value of Assets",
                                        "Net Income Two Var",
                                        "Net Working Capital",
                                        "Price to Sales Ratio",
                                        "Profit Margin",
                                        "Recievables Turnover",
                                        "Return on Assets",
                                        "Sales Per Share",
                                        "Total Debt Ratio"};
 

        public int[] chapter = { 2,
                                 2,
                                 3,
                                 2,
                                 2,
                                 2,
                                 2,
                                 3,
                                 3,
                                 3,
                                 2,
                                 3,
                                 3,
                                 3,
                                 2,
                                 2,
                                 2,
                                 3,
                                 3,
                                 3,
                                 3,
                                 3,
                                 3};

        #region
        public string[] description = {"The Average Tax Rate is the total taxes paid divided by total taxable income.",
                                        "The Book Value of Assets is the sum of the business' Book Value of Current Assets and the business' Market Value of Fixed Assets.",
                                        "The Book Value of Share is the ratio of the business' Total Equity versus the business' Shares Outstanding.",
                                        "The Cash Flow from Assets is calculated by taking the total of Cash Flow to creditors and the Cash Flow to Stockholders, this consists of the Operating Cash Flow, Capital Spending, and changes in Net Working Capital.",
                                        "The Cash flow to Creditors is taking the business' Interest paid minus the business' Net New Borrowing.",
                                        "The Cash flow to Stockholders is the ratio of the business' Dividends Paid minus the business' Net New Equity.",
                                        "The Change in Net Working Capital is calculated by taking the end of period Net Working Capital minus the beginning of period Net Working Capital.",
                                        "The Current Ratio is the business' Current Assets versus the business' Current Liabilities.",
                                        "The Days Sales in Inventory is teh ratio of the Number of Days versus the business' Inventory Turnover.",
                                        "The Days Sales in Receivables ratio of the Number of Days versus the Receivables Turnover.",
                                        "The Dividends Per Share is ratio of the business' Total Dividends versus the business’ Shares Outstanding.",
                                        "The Earnings Per Share or the EPS is the ratio of the business’ Net Income versus the business’ Shares Outstanding.",
                                        "The Inventory Turnover is the ratio of the business’ Cost of Goods Sold versus the business’ Inventory.",
                                        "The Market to Book Ratio is the business’ Share Price versus the business’ Book Value Per Share.",
                                        "The Market Value of Assets is the sum of the business’ Market Value of Current Assets and the business’ Market Value of the Fixed Assets.",
                                        "The Net Income is the sum of the business’ Dividends and the business’ Addition to Retained Earnings.",
                                        "The Net Working Capital is calculated by taking the business’ Current Assets and subtracting them by the business’ Current Liabililities.",
                                        "The Price to Sales Ratio is the business’ Share Price versus the businesses Sales Per Share.",
                                        "The Profit Margin is the ratio of the business’ Net Income versus the business’ Sales.",
                                        "The Receivables Turnover is the ratio of the business’ Credit Sales versus the business’ Receivables.",
                                        "The Return on Assets is the ratio of the business’ Net Income versus the business’ Total Assets.",
                                        "The Sales Per Share is the ratio of the business’ Total Sales versus the business’ Shares Outstanding.",
                                        "The Total Debt Ratio is the business’ Total Debt versus the business’ Total Assets"};
        #endregion
        #region
        public string[] firstVarName = {"Total Tax",
                                        "Book Value of Current Assets",
                                        "Total Equity",
                                        "Cash Flow to Creditors",
                                        "Interest Paid",
                                        "Dividends Paid",
                                        "Final Net Working Capital",
                                        "Current Assets",
                                        "Number of Days",
                                        "Number of Days",
                                        "Total Dividends",
                                        "Net Income",
                                        "Cost of Goods Sold",
                                        "Share Price",
                                        "Market Value of Current Assets",
                                        "Dividends",
                                        "Current Assets",
                                        "Share Price",
                                        "Net Income",
                                        "Credit Sales",
                                        "Net Income",
                                        "Total Sales",
                                        "Total Debt"};
        
        public string[] secondVarName ={"Net Income",
                                        "Market Value of Fixed Assets",
                                        "Shares Outstanding",
                                        "Cash Flow to Stockholders",
                                        "Net New Borrowing",
                                        "Net New Equity",
                                        "Initial Net Working Capital",
                                        "Current Liabilities",
                                        "Inventory Turnover",
                                        "Recievables Turnover",
                                        "Shares Outstanding",
                                        "Shares Outstanding",
                                        "Inventory",
                                        "Book Value Per Share",
                                        "Market Value of Fixed Assets",
                                        "Addition to Retained Earnings",
                                        "Current Liabilities",
                                        "Sales Per Share",
                                        "Sales",
                                        "Recievables",
                                        "Total Assets",
                                        "Shares Outstanding",
                                        "Total Assets"};
        #endregion
        #region
        public string[] equationOperator = {"/",
                                            "+",
                                            "/",
                                            "+",
                                            "-",
                                            "-",
                                            "-",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "+",
                                            "+",
                                            "-",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "/",
                                            "/"};
        #endregion
        public string[] resultType =   {"Percent",
                                        "Dollar",
                                        "Dollar",
                                        "Dollar",
                                        "Dollar",
                                        "Dollar",
                                        "Dollar",
                                        "Ratio",
                                        "Days",
                                        "Days",
                                        "Dollar",
                                        "Dollar",
                                        "Ratio",
                                        "Ratio",
                                        "Dollar",
                                        "Dollar",
                                        "Dollar",
                                        "Ratio",
                                        "Percent",
                                        "Ratio",
                                        "Percent",
                                        "Dollar",
                                        "Ratio"};
        public double firstVariable { get; set; }
        public double secondVariable{ get; set; }
        public double result { get; set; }
        //protected string myOperator { get; set; }
    }
}